### PR TITLE
Fix README.MD typo

### PR DESCRIPTION
**Pull request by pmilic021**
While using the `label-checker` I noticed this doc error.

### CODE REVIEW

**Comment by johnboyes** [comment]
Hi @pmilic021, thanks for this, good spot!

If it's ok, would you be able to change the commit message in your PR to be `Fix README.MD typo`, please?  The project [uses](https://github.com/agilepathway/label-checker/blob/master/CONTRIBUTING.md#how-to-make-a-contribution) an [opinionated commit checker](https://github.com/mristin/opinionated-commit-message#readme) to ensure commit messages [start with an imperative](https://cbea.ms/git-commit/#imperative), as well as the other guidelines in [the same canonical guide by Chris Beams](https://cbea.ms/git-commit).

Hope that's ok!

Looks like I also need to amend the CI/CD pipeline to have forked PRs like this one trigger the pipeline properly - I'll get that done by this weekend hopefully.

**Comment by pmilic021** [comment]
Done, thanks for the hint!

**Comment by johnboyes** [comment]
Hi @pmilic021, sorry for the delay in getting this PR sorted.  I had to make a change on my side to enable the GitHub Actions workflows to run for PRs from forks.  I'd be very grateful if you could sync your fork by [fetching the latest upstream](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-from-the-web-ui), and then we should be good to to.  Thanks again!

**Comment by johnboyes** [comment]
A rebase would be great if that's ok, cleaner than the merge commit - thanks!

**Review by johnboyes — APPROVED** [review]

**Pull request merged**
