### PR TITLE
Add github enterprise support

### PR DESCRIPTION
**Pull request by Jacoby6000**
Github enterprise just needs a different endpoint to make this work.  
Luckily its provided by github's env vars

### CODE REVIEW

**Comment by Jacoby6000** [comment]
Let me know if  there's anything I need to do to get these workflows running.

**Comment by johnboyes** [comment]
> Let me know if there's anything I need to do to get these workflows running.

Hi @Jacoby6000, thanks v much for the PR and apologies for radio silence until now.  

I think I have some changes to do on my side to get the workflows working nicely for PRs from forked repos.  Currently I have a bunch of status checks for push events, but pushes from forked repos are not picked up.  So I think I need to reconfigure my workflow checks to run on pull requests instead of or as well as on pushes.  I should be able to get that done in the next few days if that's ok?

**Comment by Jacoby6000** [comment]
No hurry at all, was just curious if I needed to do anything

**Comment by johnboyes** [comment]
Hi @Jacoby6000, I've [made the change](https://github.com/agilepathway/label-checker/commit/698e123ce67731a27027045b2579e4ad0d0963a4)  to now allow the GitHub Actions workflows to run properly as status checks on PRs from forks such as this one.

Very grateful if you can do the following to get the PR into shape, pls:
1. Sync your fork by [fetching the latest upstream](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-from-the-web-ui)
2. I'd be grateful if you could rewrite your commits in the PR to be more informative as per the [style guide](https://cbea.ms/git-commit/) outlined in the [CONTRIBUTING.md](https://github.com/agilepathway/label-checker/blob/master/CONTRIBUTING.md#how-to-make-a-contribution) (one of the PR status checks checks that the commit messages conform to this style)

Hope that's ok, any questions please let me know, and thanks again for the contribution :-)

**Comment by Jacoby6000** [comment]
Does that work? I squashed everything to a single commit and put a clear message i think

**Comment by johnboyes** [comment]
Thanks @Jacoby6000, yep that worked nicely.  The only workflow that is failing now is the [Go linting check](https://github.com/agilepathway/label-checker/runs/5342902178?check_suite_focus=true).  To fix that, would be grateful if you could run [golangci-lint](https://golangci-lint.run/) locally, using [the project's golangci-lint configuration file](https://github.com/agilepathway/label-checker/blob/master/.golangci.yml).  On my side I will amend the [CONTRIBUTING](https://github.com/agilepathway/label-checker/blob/master/CONTRIBUTING.md) to document this for future contributors.  Really appreciate it, your PR is really helping me to make it easier for others to contribute in future 🙏🏻

**Comment by Jacoby6000** [comment]
> Thanks @Jacoby6000, yep that worked nicely. The only workflow that is failing now is the [Go linting check](https://github.com/agilepathway/label-checker/runs/5342902178?check_suite_focus=true). To fix that, would be grateful if you could run [golangci-lint](https://golangci-lint.run/) locally, using [the project's golangci-lint configuration file](https://github.com/agilepathway/label-checker/blob/master/.golangci.yml). On my side I will amend the [CONTRIBUTING](https://github.com/agilepathway/label-checker/blob/master/CONTRIBUTING.md) to document this for future contributors. Really appreciate it, your PR is really helping me to make it easier for others to contribute in future 🙏🏻

Sorry it took so long to get to this.  I've updated the PR to satisfy all the linting rules.  This is my first time "writing" go, so this tool chain is totally new to me lol.

The linter instructed me to run `gofmt -s -w .` so I did.  However that seems to have added something to label_checker.go which may be invalid.

**Comment by johnboyes** [comment]
Hi @Jacoby6000, thanks for working on the linting, especially as you're new to the toolchain, that's great!  I should be able to look at this PR properly again tomorrow.

**Comment by johnboyes** [comment]
Hi @Jacoby6000, I've _finally_ merged this, really sorry it took so long.  Before merging I added some [tests](https://github.com/agilepathway/label-checker/pull/264/commits/58bd47c74a3489280f2a6d7d6636a8e8bc4d344b) and [documentation](https://github.com/agilepathway/label-checker/pull/264/commits/f132ecf00364850280b2f2a80d56a8a0f82a8355) to the PR.

I also amended the name of the GitHub Enterprise environment variable, so that the value can be set as a [GitHub Actions input parameter](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs), e.g:

```
with:
  github_enterprise_graphql_url: https://example.com/api/graphql
```

If you have a GitHub Enterprise instance that you are using the label checker on, would be very grateful if you could confirm if it works ok for you.  🙏🏻

**Pull request merged**
